Add reaction
jadilorenzo/react-express-psql pull request #18
Opened 2020-03-05 01:52 UTC by jadilorenzo

2020-03-05 01:54 UTC, jadilorenzo commented
I branched off of #17.
<img width="1401" alt="Screen Shot 2020-03-04 at 8 54 00 PM" src="https://user-images.githubusercontent.com/46056370/75940201-5edf9500-5e5a-11ea-9af0-522f50bac036.png">

2020-03-06 00:24 UTC, rcdilorenzo requested changes

2020-03-06 00:24 UTC, rcdilorenzo commented on server/server.js
> +  pool.query(`INSERT INTO messages (mid, uid, rid, message, reaction) VALUES ($1, $2, $3, $4, $5);`, [req.body.db.mid, req.body.db.uid, req.body.db.rid, req.body.db.message,  req.body.db.reaction])
This could easily be a problem. Are you only allowing a single reaction for a message? You really want to create another table called `reactions` and have it include a `mid` (better named `message_id`).

In messages table:
```
id (PRIMARY)
value (could be character code or text)
message_id (foreign key that references mid in messages table)
```

2020-03-06 00:24 UTC, rcdilorenzo commented on src/pages/LoginPage.js
> +            const userId = getUser(users, username, input)[0].uid
You probably shouldn't be calling this function twice. Can you save it to a variable?

2020-03-06 00:24 UTC, rcdilorenzo commented on src/pages/MessagePage.js
> +          {message.name}: {message.message} { message.message !== null ? <span className='px-1 font-bold' style={{float: 'right'}}>{message.reaction}</span> : <span className='font-bold'>{message.rea
There's way too much logic here. Can we extract some of this to a function and/or component? You'll have to address my previous comment about changing the data storage (with a new table) first of course.

2020-03-06 00:24 UTC, rcdilorenzo commented on src/test/GetAccessibleRooms.test.js
> +import getAccessibleRooms from '../methods/GetAccessibleRooms'
The file structure here isn't great. You should have a logical grouping (think of a class or module). The name "methods" doesn't describe anything other than that it's a function. Also, you shouldn't be camelCasing the name if it's just a function. If you really want just one function in a single file, just use the same name (e.g. `getAccessibleRooms.js`). I'll let you figure out what you want to do from there.

2020-03-21 22:24 UTC, merged